//! Harmony mode implementations.
//!
//! This module contains the algorithm implementations for each harmony mode.
//! Each function takes an input note and mutable scale reference, returning
//! a `Vec<Note>` containing the original note plus any generated harmony notes.
//!
//! # Mode Function Signature
//!
//! All mode functions follow this pattern:
//!
//! ```text
//! fn mode_name(note: Note, scale: &mut Scale) -> Vec<Note>
//! ```
//!
//! The scale is passed as `&mut` to support modal interchange, which may
//! update the `last_borrowed_from` field when borrowing from parallel modes.
//!
//! # Return Value
//!
//! - **Success**: `[input_note, harmony_note]` (2 elements)
//! - **Out of range**: `[input_note]` (1 element, harmony couldn't be generated)
//! - **PassThrough**: `[input_note]` (1 element, no harmony generated by design)
//!
//! # Directed Variants
//!
//! Most modes have a `_directed` variant that takes an additional `above: bool`
//! parameter to control harmony direction:
//!
//! - `above = true`: Generate harmony above the input note
//! - `above = false`: Generate harmony below the input note
//!
//! These are used by [`super::HarmonyEngine`] for voice position support,
//! where harmonies may need to be generated in both directions from the
//! user's input position.
//!
//! # Algorithm Details
//!
//! ## Mode 1: Pass-Through
//! No harmony generation. Returns only the input note unchanged.
//!
//! ## Mode 2: Diatonic Thirds
//! Adds a third (2 scale degrees) above/below. For in-scale notes, uses
//! diatonic transposition. For out-of-key notes, uses modal interchange
//! (if enabled) or consonant chromatic intervals.
//!
//! ## Mode 3: Diatonic Fourths
//! Same as thirds but uses 3 scale degrees (perfect 4th in most contexts).
//!
//! ## Mode 4: Random Below
//! Chooses a random diatonic interval from 2nd to 7th below (-1 to -6 degrees).
//! The random selection happens once per Note-On; the engine tracks this for
//! consistent Note-Off release.
//!
//! ## Mode 5: Random Below No Seconds
//! Same as Mode 4 but excludes 2nds (which can sound dissonant), using
//! intervals from 3rd to 7th below (-2 to -6 degrees).
//!
//! ## Mode 8: Barry Harris
//! Moves by exactly 2 scale degrees. In 8-note Barry Harris scales, this
//! preserves chord-tone/passing-tone parity (even degrees stay even, odd
//! stay odd). Works with any scale but is musically intended for BH scales.

use rand::RngExt;
use wmidi::Note;

use crate::Scale;

/// Mode 1: Pass-through (no harmony).
///
/// Returns only the input note unchanged. This is the safest default mode
/// and is useful for testing MIDI routing without harmony generation.
pub fn pass_through(note: Note, _scale: &mut Scale) -> Vec<Note> {
    vec![note]
}

/// Mode 2: Diatonic thirds above.
///
/// Returns the input note plus a diatonic third (2 scale degrees) above.
///
/// # Algorithm
///
/// 1. Check if note is in scale via `scale.is_in_scale(note)`
/// 2. If in-scale: Use `scale.transpose_diatonic(note, 2)` for exact interval
/// 3. If out-of-key: Use `scale.harmonize_smart()` which tries:
///    - Modal interchange (if enabled) to borrow from parallel modes
///    - Consonant chromatic intervals (3rds, 6ths) as fallback
///
/// # Returns
///
/// - `[note, harmony]` on success
/// - `[note]` if harmony would be out of MIDI range (0-127)
pub fn diatonic_thirds(note: Note, scale: &mut Scale) -> Vec<Note> {
    match scale.harmonize_smart(note, 2, true) {
        Some(harmony) => vec![note, harmony],
        None => vec![note], // Out of range, just pass through
    }
}

/// Mode 3: Diatonic fourths above.
///
/// Returns the input note plus a diatonic fourth (3 scale degrees) above.
/// For out-of-key notes, uses a consonant chromatic interval instead.
/// If harmony would be out of range, returns only the original note.
pub fn diatonic_fourths(note: Note, scale: &mut Scale) -> Vec<Note> {
    match scale.harmonize_smart(note, 3, true) {
        Some(harmony) => vec![note, harmony],
        None => vec![note],
    }
}

/// Mode 4: Random diatonic interval below.
///
/// Returns the input note plus a random diatonic interval below
/// (2nd through 7th below, i.e., -1 to -6 scale degrees).
///
/// # Random Selection
///
/// The interval is chosen randomly using `rand::thread_rng()`. For consistent
/// Note-Off handling, the [`super::HarmonyEngine`] tracks which harmony was
/// produced for each Note-On and replays it for Note-Off.
///
/// # Intervals Used
///
/// - -1 degree: 2nd below
/// - -2 degrees: 3rd below
/// - -3 degrees: 4th below
/// - -4 degrees: 5th below
/// - -5 degrees: 6th below
/// - -6 degrees: 7th below
pub fn random_below(note: Note, scale: &mut Scale) -> Vec<Note> {
    let mut rng = rand::rng();

    // Intervals: -1 (2nd below) to -6 (7th below)
    let intervals = [-1, -2, -3, -4, -5, -6];
    let interval = intervals[rng.random_range(0..intervals.len())];

    match scale.harmonize_smart(note, interval, false) {
        Some(harmony) => vec![note, harmony],
        None => vec![note],
    }
}

/// Mode 5: Random diatonic below, excluding seconds.
///
/// Like Mode 4, but excludes 2nds (which can sound dissonant).
/// Returns input plus a random interval from 3rd to 7th below.
/// For out-of-key notes, uses a consonant chromatic interval instead.
pub fn random_below_no_seconds(note: Note, scale: &mut Scale) -> Vec<Note> {
    let mut rng = rand::rng();

    // Intervals: -2 (3rd below) to -6 (7th below), skipping -1 (2nd)
    let intervals = [-2, -3, -4, -5, -6];
    let interval = intervals[rng.random_range(0..intervals.len())];

    match scale.harmonize_smart(note, interval, false) {
        Some(harmony) => vec![note, harmony],
        None => vec![note],
    }
}

// --- Directed variants for voice position ---
// These take an `above: bool` parameter to control harmony direction.
// When `above` is true, harmony is generated above the input note.
// When `above` is false, harmony is generated below.

/// Try `harmonize_smart`; if it would land out of MIDI range [0, 127],
/// retry with the input octave-shifted toward the center of the range so
/// the chain doesn't silently drop voices at register edges. Direction
/// (above/below) is honored on the first attempt; the wrap fallback may
/// land the harmony on either side of the input but keeps the voice
/// audible — the harmonize() chain caller stitches results together by
/// arrangement slot, not by pitch ordering.
fn harmonize_smart_or_wrap(
    scale: &mut Scale,
    note: Note,
    degrees: i8,
    above: bool,
) -> Option<Note> {
    if let Some(h) = scale.harmonize_smart(note, degrees, above) {
        return Some(h);
    }
    let m = u8::from(note) as i16;
    // Try shifting input toward MIDI center (60). Order favors the shift
    // direction that "undoes" the overflow: if we asked for above and
    // failed, the harmony was too high — pull input down. If we asked for
    // below and failed, pull input up.
    let shifts: [i16; 4] = if above {
        [-12, -24, 12, 24]
    } else {
        [12, 24, -12, -24]
    };
    for off in shifts {
        let shifted = m + off;
        if !(0..=127).contains(&shifted) {
            continue;
        }
        if let Ok(shifted_note) = Note::try_from(shifted as u8) {
            if let Some(h) = scale.harmonize_smart(shifted_note, degrees, above) {
                return Some(h);
            }
        }
    }
    None
}

/// Directed diatonic thirds: above or below the input note.
///
/// Used by [`super::HarmonyEngine`] for multi-voice generation where
/// harmonies need to be generated in both directions from the user's
/// voice position.
pub fn diatonic_thirds_directed(note: Note, scale: &mut Scale, above: bool) -> Vec<Note> {
    let interval = if above { 2 } else { -2 };
    match harmonize_smart_or_wrap(scale, note, interval, above) {
        Some(harmony) => vec![note, harmony],
        None => vec![note],
    }
}

/// Directed diatonic fourths: above or below the input note.
pub fn diatonic_fourths_directed(note: Note, scale: &mut Scale, above: bool) -> Vec<Note> {
    let interval = if above { 3 } else { -3 };
    match harmonize_smart_or_wrap(scale, note, interval, above) {
        Some(harmony) => vec![note, harmony],
        None => vec![note],
    }
}

/// Directed random diatonic interval.
///
/// - `above = true`: Random 2nd-7th above (+1 to +6 degrees)
/// - `above = false`: Random 2nd-7th below (-1 to -6 degrees)
pub fn random_directed(note: Note, scale: &mut Scale, above: bool) -> Vec<Note> {
    let mut rng = rand::rng();
    let intervals: [i8; 6] = if above {
        [1, 2, 3, 4, 5, 6]
    } else {
        [-1, -2, -3, -4, -5, -6]
    };
    let interval = intervals[rng.random_range(0..intervals.len())];

    match harmonize_smart_or_wrap(scale, note, interval, above) {
        Some(harmony) => vec![note, harmony],
        None => vec![note],
    }
}

/// Directed random diatonic interval, excluding seconds.
///
/// - `above = true`: Random 3rd-7th above (+2 to +6 degrees)
/// - `above = false`: Random 3rd-7th below (-2 to -6 degrees)
pub fn random_no_seconds_directed(note: Note, scale: &mut Scale, above: bool) -> Vec<Note> {
    let mut rng = rand::rng();
    let intervals: [i8; 5] = if above {
        [2, 3, 4, 5, 6]
    } else {
        [-2, -3, -4, -5, -6]
    };
    let interval = intervals[rng.random_range(0..intervals.len())];

    match harmonize_smart_or_wrap(scale, note, interval, above) {
        Some(harmony) => vec![note, harmony],
        None => vec![note],
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_pass_through() {
        let mut scale = Scale::major(0);
        let result = pass_through(Note::C4, &mut scale);
        assert_eq!(result, vec![Note::C4]);
    }

    #[test]
    fn test_diatonic_thirds() {
        let mut scale = Scale::major(0); // C major

        // C4 + third = E4
        let result = diatonic_thirds(Note::C4, &mut scale);
        assert_eq!(result, vec![Note::C4, Note::E4]);

        // E4 + third = G4 (minor third, but still 2 scale degrees)
        let result = diatonic_thirds(Note::E4, &mut scale);
        assert_eq!(result, vec![Note::E4, Note::G4]);
    }

    #[test]
    fn test_diatonic_fourths() {
        let mut scale = Scale::major(0);

        // C4 + fourth = F4
        let result = diatonic_fourths(Note::C4, &mut scale);
        assert_eq!(result, vec![Note::C4, Note::F4]);
    }

    #[test]
    fn test_random_below_produces_harmony() {
        let mut scale = Scale::major(0);

        // Should produce 2 notes (original + harmony below)
        let result = random_below(Note::C5, &mut scale);
        assert_eq!(result.len(), 2);
        assert_eq!(result[0], Note::C5);

        // Harmony should be lower than input
        let harmony_midi: u8 = result[1].into();
        let input_midi: u8 = Note::C5.into();
        assert!(harmony_midi < input_midi);
    }
}
