use super::StylePreset;
use crate::harmony::{HarmonyMode, Key, OctaveMode, ScaleMode, VoiceLeadingStyle};

/// Returns all built-in presets with character personas.
pub fn all() -> Vec<StylePreset> {
    vec![
        StylePreset {
            name: "Jazz".into(),
            persona: "The Alchemist".into(),
            genre: "Jazz".into(),
            harmony_mode: HarmonyMode::StrictCounterpoint,
            key: Key::C,
            voice_leading_enabled: true,
            voice_leading_style: VoiceLeadingStyle::Jazz,
            octave_mode: OctaveMode::None,
            scale_mode: ScaleMode::Ionian,
            interchange_enabled: false,
            borrowing_range: 3,
            is_builtin: true,
        },
        StylePreset {
            name: "Classical".into(),
            persona: "The Architect".into(),
            genre: "Classical".into(),
            harmony_mode: HarmonyMode::DiatonicThirds,
            key: Key::C,
            voice_leading_enabled: true,
            voice_leading_style: VoiceLeadingStyle::BachChorale,
            octave_mode: OctaveMode::None,
            scale_mode: ScaleMode::Ionian,
            interchange_enabled: false,
            borrowing_range: 3,
            is_builtin: true,
        },
        StylePreset {
            name: "Pop".into(),
            persona: "The Bard".into(),
            genre: "Pop".into(),
            harmony_mode: HarmonyMode::DiatonicThirds,
            key: Key::C,
            voice_leading_enabled: false,
            voice_leading_style: VoiceLeadingStyle::Free,
            octave_mode: OctaveMode::None,
            scale_mode: ScaleMode::Ionian,
            interchange_enabled: false,
            borrowing_range: 3,
            is_builtin: true,
        },
        StylePreset {
            name: "Baroque".into(),
            persona: "The Clockmaker".into(),
            genre: "Baroque".into(),
            harmony_mode: HarmonyMode::StrictCounterpoint,
            key: Key::C,
            voice_leading_enabled: true,
            voice_leading_style: VoiceLeadingStyle::Palestrina,
            octave_mode: OctaveMode::Spread,
            scale_mode: ScaleMode::Ionian,
            interchange_enabled: false,
            borrowing_range: 3,
            is_builtin: true,
        },
        StylePreset {
            name: "Minimal".into(),
            persona: "The Monk".into(),
            genre: "Minimal".into(),
            harmony_mode: HarmonyMode::PassThrough,
            key: Key::C,
            voice_leading_enabled: false,
            voice_leading_style: VoiceLeadingStyle::Free,
            octave_mode: OctaveMode::None,
            scale_mode: ScaleMode::Ionian,
            interchange_enabled: false,
            borrowing_range: 3,
            is_builtin: true,
        },
        StylePreset {
            name: "Lo-fi".into(),
            persona: "The Phantom".into(),
            genre: "Lo-fi".into(),
            harmony_mode: HarmonyMode::RandomBelow,
            key: Key::C,
            voice_leading_enabled: false,
            voice_leading_style: VoiceLeadingStyle::Free,
            octave_mode: OctaveMode::None,
            scale_mode: ScaleMode::Ionian,
            interchange_enabled: false,
            borrowing_range: 3,
            is_builtin: true,
        },
        StylePreset {
            name: "Ambient".into(),
            persona: "The Seer".into(),
            genre: "Ambient".into(),
            harmony_mode: HarmonyMode::DiatonicFourths,
            key: Key::C,
            voice_leading_enabled: true,
            voice_leading_style: VoiceLeadingStyle::Free,
            octave_mode: OctaveMode::Mirror,
            scale_mode: ScaleMode::Ionian,
            interchange_enabled: false,
            borrowing_range: 3,
            is_builtin: true,
        },
        StylePreset {
            name: "Gospel".into(),
            persona: "The Preacher".into(),
            genre: "Gospel".into(),
            harmony_mode: HarmonyMode::ContraryMotion,
            key: Key::C,
            voice_leading_enabled: true,
            voice_leading_style: VoiceLeadingStyle::Free,
            octave_mode: OctaveMode::BassTrebleSplit,
            scale_mode: ScaleMode::Ionian,
            interchange_enabled: false,
            borrowing_range: 3,
            is_builtin: true,
        },
        StylePreset {
            name: "Metal".into(),
            persona: "The Forge".into(),
            genre: "Metal".into(),
            harmony_mode: HarmonyMode::RandomBelowNoSeconds,
            key: Key::C,
            voice_leading_enabled: true,
            voice_leading_style: VoiceLeadingStyle::Palestrina,
            octave_mode: OctaveMode::Spread,
            scale_mode: ScaleMode::Ionian,
            interchange_enabled: false,
            borrowing_range: 3,
            is_builtin: true,
        },
        StylePreset {
            name: "Prog".into(),
            persona: "The Voyager".into(),
            genre: "Prog".into(),
            harmony_mode: HarmonyMode::StrictCounterpoint,
            key: Key::C,
            voice_leading_enabled: true,
            voice_leading_style: VoiceLeadingStyle::BachChorale,
            octave_mode: OctaveMode::Mirror,
            scale_mode: ScaleMode::Ionian,
            interchange_enabled: false,
            borrowing_range: 3,
            is_builtin: true,
        },
        StylePreset {
            name: "Soul".into(),
            persona: "The Spirit".into(),
            genre: "Soul".into(),
            harmony_mode: HarmonyMode::DiatonicThirds,
            key: Key::C,
            voice_leading_enabled: true,
            voice_leading_style: VoiceLeadingStyle::Jazz,
            octave_mode: OctaveMode::None,
            scale_mode: ScaleMode::Ionian,
            interchange_enabled: false,
            borrowing_range: 3,
            is_builtin: true,
        },
    ]
}
