use super::StylePreset;
use crate::harmony::{Key, HarmonyMode, OctaveMode, ScaleMode, VoiceLeadingStyle};
use crate::humanize::HumanizeConfig;

/// Returns all built-in presets with character personas.
pub fn all() -> Vec<StylePreset> {
    vec![
        StylePreset {
            name: "Jazz".into(),
            persona: "The Alchemist".into(),
            genre: "Jazz".into(),
            harmony_mode: HarmonyMode::StrictCounterpoint,
            key: Key::C,
            voice_leading_enabled: true,
            voice_leading_style: VoiceLeadingStyle::Jazz,
            octave_mode: OctaveMode::None,
            humanize_config: HumanizeConfig {
                enabled: true,
                jitter_enabled: true,
                jitter_min_ms: 5,
                jitter_max_ms: 25,
                velocity_enabled: true,
                velocity_variation: 12,
                duration_enabled: true,
                duration_variation_ms: 30,
                swing_enabled: true,
                swing_amount: 0.55,
                ..HumanizeConfig::default()
            },
            scale_mode: ScaleMode::Ionian,
            interchange_enabled: false,
            borrowing_range: 3,
            is_builtin: true,
        },
        StylePreset {
            name: "Classical".into(),
            persona: "The Architect".into(),
            genre: "Classical".into(),
            harmony_mode: HarmonyMode::DiatonicThirds,
            key: Key::C,
            voice_leading_enabled: true,
            voice_leading_style: VoiceLeadingStyle::BachChorale,
            octave_mode: OctaveMode::None,
            humanize_config: HumanizeConfig {
                enabled: true,
                jitter_enabled: true,
                jitter_min_ms: 1,
                jitter_max_ms: 8,
                velocity_enabled: true,
                velocity_variation: 5,
                duration_enabled: false,
                duration_variation_ms: 10,
                swing_enabled: false,
                swing_amount: 0.0,
                ..HumanizeConfig::default()
            },
            scale_mode: ScaleMode::Ionian,
            interchange_enabled: false,
            borrowing_range: 3,
            is_builtin: true,
        },
        StylePreset {
            name: "Pop".into(),
            persona: "The Bard".into(),
            genre: "Pop".into(),
            harmony_mode: HarmonyMode::DiatonicThirds,
            key: Key::C,
            voice_leading_enabled: false,
            voice_leading_style: VoiceLeadingStyle::Free,
            octave_mode: OctaveMode::None,
            humanize_config: HumanizeConfig {
                enabled: true,
                jitter_enabled: true,
                jitter_min_ms: 2,
                jitter_max_ms: 12,
                velocity_enabled: true,
                velocity_variation: 10,
                duration_enabled: false,
                duration_variation_ms: 15,
                swing_enabled: true,
                swing_amount: 0.2,
                ..HumanizeConfig::default()
            },
            scale_mode: ScaleMode::Ionian,
            interchange_enabled: false,
            borrowing_range: 3,
            is_builtin: true,
        },
        StylePreset {
            name: "Baroque".into(),
            persona: "The Clockmaker".into(),
            genre: "Baroque".into(),
            harmony_mode: HarmonyMode::StrictCounterpoint,
            key: Key::C,
            voice_leading_enabled: true,
            voice_leading_style: VoiceLeadingStyle::Palestrina,
            octave_mode: OctaveMode::Spread,
            humanize_config: HumanizeConfig {
                enabled: true,
                jitter_enabled: true,
                jitter_min_ms: 1,
                jitter_max_ms: 6,
                velocity_enabled: true,
                velocity_variation: 4,
                duration_enabled: false,
                duration_variation_ms: 5,
                swing_enabled: false,
                swing_amount: 0.0,
                ..HumanizeConfig::default()
            },
            scale_mode: ScaleMode::Ionian,
            interchange_enabled: false,
            borrowing_range: 3,
            is_builtin: true,
        },
        StylePreset {
            name: "Minimal".into(),
            persona: "The Monk".into(),
            genre: "Minimal".into(),
            harmony_mode: HarmonyMode::PassThrough,
            key: Key::C,
            voice_leading_enabled: false,
            voice_leading_style: VoiceLeadingStyle::Free,
            octave_mode: OctaveMode::None,
            humanize_config: HumanizeConfig {
                enabled: true,
                jitter_enabled: true,
                jitter_min_ms: 1,
                jitter_max_ms: 3,
                velocity_enabled: true,
                velocity_variation: 3,
                duration_enabled: false,
                duration_variation_ms: 5,
                swing_enabled: false,
                swing_amount: 0.0,
                ..HumanizeConfig::default()
            },
            scale_mode: ScaleMode::Ionian,
            interchange_enabled: false,
            borrowing_range: 3,
            is_builtin: true,
        },
        StylePreset {
            name: "Lo-fi".into(),
            persona: "The Phantom".into(),
            genre: "Lo-fi".into(),
            harmony_mode: HarmonyMode::RandomBelow,
            key: Key::C,
            voice_leading_enabled: false,
            voice_leading_style: VoiceLeadingStyle::Free,
            octave_mode: OctaveMode::None,
            humanize_config: HumanizeConfig {
                enabled: true,
                jitter_enabled: true,
                jitter_min_ms: 8,
                jitter_max_ms: 30,
                velocity_enabled: true,
                velocity_variation: 18,
                duration_enabled: true,
                duration_variation_ms: 40,
                swing_enabled: true,
                swing_amount: 0.65,
                ..HumanizeConfig::default()
            },
            scale_mode: ScaleMode::Ionian,
            interchange_enabled: false,
            borrowing_range: 3,
            is_builtin: true,
        },
        StylePreset {
            name: "Ambient".into(),
            persona: "The Seer".into(),
            genre: "Ambient".into(),
            harmony_mode: HarmonyMode::DiatonicFourths,
            key: Key::C,
            voice_leading_enabled: true,
            voice_leading_style: VoiceLeadingStyle::Free,
            octave_mode: OctaveMode::Mirror,
            humanize_config: HumanizeConfig {
                enabled: true,
                jitter_enabled: true,
                jitter_min_ms: 2,
                jitter_max_ms: 8,
                velocity_enabled: true,
                velocity_variation: 10,
                duration_enabled: true,
                duration_variation_ms: 50,
                swing_enabled: false,
                swing_amount: 0.0,
                ..HumanizeConfig::default()
            },
            scale_mode: ScaleMode::Ionian,
            interchange_enabled: false,
            borrowing_range: 3,
            is_builtin: true,
        },
        StylePreset {
            name: "Gospel".into(),
            persona: "The Preacher".into(),
            genre: "Gospel".into(),
            harmony_mode: HarmonyMode::ContraryMotion,
            key: Key::C,
            voice_leading_enabled: true,
            voice_leading_style: VoiceLeadingStyle::Free,
            octave_mode: OctaveMode::BassTrebleSplit,
            humanize_config: HumanizeConfig {
                enabled: true,
                jitter_enabled: true,
                jitter_min_ms: 3,
                jitter_max_ms: 15,
                velocity_enabled: true,
                velocity_variation: 18,
                duration_enabled: false,
                duration_variation_ms: 20,
                swing_enabled: true,
                swing_amount: 0.4,
                ..HumanizeConfig::default()
            },
            scale_mode: ScaleMode::Ionian,
            interchange_enabled: false,
            borrowing_range: 3,
            is_builtin: true,
        },
        StylePreset {
            name: "Metal".into(),
            persona: "The Forge".into(),
            genre: "Metal".into(),
            harmony_mode: HarmonyMode::RandomBelowNoSeconds,
            key: Key::C,
            voice_leading_enabled: true,
            voice_leading_style: VoiceLeadingStyle::Palestrina,
            octave_mode: OctaveMode::Spread,
            humanize_config: HumanizeConfig {
                enabled: true,
                jitter_enabled: true,
                jitter_min_ms: 1,
                jitter_max_ms: 5,
                velocity_enabled: true,
                velocity_variation: 20,
                duration_enabled: false,
                duration_variation_ms: 10,
                swing_enabled: false,
                swing_amount: 0.0,
                ..HumanizeConfig::default()
            },
            scale_mode: ScaleMode::Ionian,
            interchange_enabled: false,
            borrowing_range: 3,
            is_builtin: true,
        },
        StylePreset {
            name: "Prog".into(),
            persona: "The Voyager".into(),
            genre: "Prog".into(),
            harmony_mode: HarmonyMode::StrictCounterpoint,
            key: Key::C,
            voice_leading_enabled: true,
            voice_leading_style: VoiceLeadingStyle::BachChorale,
            octave_mode: OctaveMode::Mirror,
            humanize_config: HumanizeConfig {
                enabled: true,
                jitter_enabled: true,
                jitter_min_ms: 3,
                jitter_max_ms: 12,
                velocity_enabled: true,
                velocity_variation: 10,
                duration_enabled: true,
                duration_variation_ms: 20,
                swing_enabled: true,
                swing_amount: 0.3,
                ..HumanizeConfig::default()
            },
            scale_mode: ScaleMode::Ionian,
            interchange_enabled: false,
            borrowing_range: 3,
            is_builtin: true,
        },
        StylePreset {
            name: "Soul".into(),
            persona: "The Spirit".into(),
            genre: "Soul".into(),
            harmony_mode: HarmonyMode::DiatonicThirds,
            key: Key::C,
            voice_leading_enabled: true,
            voice_leading_style: VoiceLeadingStyle::Jazz,
            octave_mode: OctaveMode::None,
            humanize_config: HumanizeConfig {
                enabled: true,
                jitter_enabled: true,
                jitter_min_ms: 3,
                jitter_max_ms: 15,
                velocity_enabled: true,
                velocity_variation: 16,
                duration_enabled: true,
                duration_variation_ms: 25,
                swing_enabled: true,
                swing_amount: 0.5,
                ..HumanizeConfig::default()
            },
            scale_mode: ScaleMode::Ionian,
            interchange_enabled: false,
            borrowing_range: 3,
            is_builtin: true,
        },
    ]
}
