# fly.toml app configuration file generated for contrapunk on 2026-01-29T02:42:27+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'contrapunk'
primary_region = 'ewr'

[build]
  dockerfile = "deploy/Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
