//! Managed Tauri state wrapping HarmonyEngine and related components.
//!
//! AppState is registered with Tauri's managed state system and accessed
//! via `State<AppState>` in command handlers.

use std::collections::HashSet;
use std::sync::atomic::AtomicBool;
use std::sync::Mutex;

use contrapunk::harmony::{HarmonyEngine, Key, HarmonyMode};
use contrapunk::humanize::HumanizeConfig;
use contrapunk::preset::PresetManager;

/// Application state managed by Tauri.
///
/// Wraps the core harmony engine, humanization config, preset manager,
/// and real-time note state in thread-safe containers for access from
/// both the main thread (command handlers) and the router thread.
pub struct AppState {
    /// Core harmony engine (key, mode, scale, voice leading, etc.)
    pub engine: Mutex<HarmonyEngine>,

    /// Humanization configuration
    pub humanize_config: Mutex<HumanizeConfig>,

    /// Preset manager for built-in and custom presets
    pub preset_manager: Mutex<PresetManager>,

    /// Whether MIDI routing is currently active
    pub is_running: AtomicBool,

    /// MIDI note numbers currently held on input (melody)
    pub input_notes: Mutex<HashSet<u8>>,

    /// MIDI note numbers generated by harmony engine
    pub harmony_notes: Mutex<HashSet<u8>>,

    /// MIDI note numbers borrowed from another mode via interchange
    pub borrowed_notes: Mutex<HashSet<u8>>,

    /// Currently detected chord name
    pub chord_name: Mutex<String>,
}

impl Default for AppState {
    fn default() -> Self {
        Self {
            engine: Mutex::new(HarmonyEngine::new(Key::C, HarmonyMode::PassThrough)),
            humanize_config: Mutex::new(HumanizeConfig::default()),
            preset_manager: Mutex::new(PresetManager::new()),
            is_running: AtomicBool::new(false),
            input_notes: Mutex::new(HashSet::new()),
            harmony_notes: Mutex::new(HashSet::new()),
            borrowed_notes: Mutex::new(HashSet::new()),
            chord_name: Mutex::new(String::new()),
        }
    }
}
