//! Managed Tauri state wrapping HarmonyEngine and related components.
//!
//! AppState is registered with Tauri's managed state system and accessed
//! via `State<AppState>` in command handlers.

use std::collections::HashSet;
use std::sync::atomic::{AtomicBool, AtomicI32};
use std::sync::mpsc;
use std::sync::{Arc, Mutex};

use contrapunk::audio::guitar_input::GuitarInputConfig;
use contrapunk::harmony::{HarmonyEngine, HarmonyMode, Key, RoutingMode};
use contrapunk::preset::PresetManager;
use contrapunk::synth::{SynthEvent, SynthParams};
use contrapunk::transport::Transport;

/// Application state managed by Tauri.
///
/// Wraps the core harmony engine, humanization config, preset manager,
/// and real-time note state in thread-safe containers for access from
/// both the main thread (command handlers) and the router thread.
pub struct AppState {
    /// Core harmony engine (key, mode, scale, voice leading, etc.)
    pub engine: Mutex<HarmonyEngine>,

    /// Preset manager for built-in and custom presets
    pub preset_manager: Mutex<PresetManager>,

    /// Whether MIDI routing is currently active
    pub is_running: AtomicBool,

    /// MIDI note numbers currently held on input (melody)
    pub input_notes: Mutex<HashSet<u8>>,

    /// MIDI note numbers generated by harmony engine
    pub harmony_notes: Mutex<HashSet<u8>>,

    /// MIDI note numbers borrowed from another mode via interchange
    pub borrowed_notes: Mutex<HashSet<u8>>,

    /// Currently detected chord name
    pub chord_name: Mutex<String>,

    /// Guitar input DSP configuration (None = use defaults)
    pub guitar_config: Mutex<Option<GuitarInputConfig>>,

    /// Guitar audio device name (empty = default input device)
    pub guitar_device: Mutex<String>,

    /// Guitar audio channel index (0-based, e.g. 0 = left, 1 = right)
    pub guitar_channel: Mutex<usize>,

    /// MIDI routing mode (channel-based MPE or port-based)
    pub routing_mode: Mutex<RoutingMode>,

    /// Stop signal for the router thread — set to true to stop the current routing
    pub stop_signal: Mutex<Option<Arc<AtomicBool>>>,

    /// Sender half of the router thread's MIDI input channel. Populated when
    /// routing starts so that `inject_note_on` / `inject_note_off` (virtual
    /// input from the UI) can push directly into the same pipeline physical
    /// MIDI + guitar audio already feed.
    pub router_tx: Mutex<Option<mpsc::Sender<Vec<u8>>>>,

    /// Flag raised by command handlers after any engine mutation that could
    /// leave notes stuck (key/mode/scale/voices change). The router thread
    /// clears it each loop by emitting MIDI All-Notes-Off on every channel
    /// across every port and clearing tracked note state.
    pub panic_pending: Arc<AtomicBool>,

    /// Global detune in cents. Read by the router thread each frame (lock-free).
    /// Updated by the `set_detune` command.
    pub detune_cents: Arc<AtomicI32>,

    /// Sample-accurate transport clock. Driven by the audio-output
    /// callback (see `audio_clock`). Shared across command threads and
    /// the audio thread via atomics.
    pub transport: Arc<Transport>,

    /// Metronome audible-click toggle. Read by the audio callback on
    /// every beat crossing; no click synthesis when false. Off by default
    /// so enabling the transport doesn't produce surprise audio.
    pub metronome_enabled: Arc<AtomicBool>,

    /// Built-in synth parameters (waveform, ADSR, filter, master gain).
    /// Read by the audio callback each buffer; mutated by Tauri command
    /// handlers in response to UI changes.
    pub synth_params: Arc<SynthParams>,

    /// Sender half of the synth's MIDI-event channel. The router thread
    /// pushes events here whenever harmony produces a note-on/off; the
    /// audio callback drains the receiver end on every buffer.
    pub synth_tx: mpsc::Sender<SynthEvent>,

    /// Receiver, stored in an Option so the audio_clock setup hook can
    /// `.take()` it and move it into the stream callback.
    pub synth_rx: Mutex<Option<mpsc::Receiver<SynthEvent>>>,
}

impl Default for AppState {
    fn default() -> Self {
        Self {
            engine: Mutex::new(HarmonyEngine::new(Key::C, HarmonyMode::PassThrough)),
            preset_manager: Mutex::new(PresetManager::new()),
            is_running: AtomicBool::new(false),
            input_notes: Mutex::new(HashSet::new()),
            harmony_notes: Mutex::new(HashSet::new()),
            borrowed_notes: Mutex::new(HashSet::new()),
            chord_name: Mutex::new(String::new()),
            guitar_config: Mutex::new(None),
            guitar_device: Mutex::new(String::new()),
            guitar_channel: Mutex::new(0),
            routing_mode: Mutex::new(RoutingMode::default()),
            stop_signal: Mutex::new(None),
            router_tx: Mutex::new(None),
            panic_pending: Arc::new(AtomicBool::new(false)),
            detune_cents: Arc::new(AtomicI32::new(0)),
            // Placeholder sample rate; audio_clock::start() corrects it
            // to the actual cpal device rate at app launch.
            transport: Transport::new(48_000),
            metronome_enabled: Arc::new(AtomicBool::new(false)),
            synth_params: Arc::new(SynthParams::default()),
            synth_tx: {
                let (tx, _) = mpsc::channel();
                tx
            },
            synth_rx: Mutex::new(None),
        }
    }
}

impl AppState {
    /// Build AppState with a freshly-connected synth MIDI channel. Use
    /// this instead of `default()` so the audio-clock setup hook has a
    /// matching rx to `.take()`.
    pub fn new() -> Self {
        let mut base = Self::default();
        let (tx, rx) = mpsc::channel::<SynthEvent>();
        base.synth_tx = tx;
        base.synth_rx = Mutex::new(Some(rx));
        base
    }
}
