//! Managed Tauri state wrapping HarmonyEngine and related components.
//!
//! AppState is registered with Tauri's managed state system and accessed
//! via `State<AppState>` in command handlers.

use std::collections::HashSet;
use std::sync::atomic::{AtomicBool, AtomicI32};
use std::sync::{Arc, Mutex};

use contrapunk::audio::guitar_input::GuitarInputConfig;
use contrapunk::audio_out::{AudioOutEngine, MidiProducer};
use contrapunk::generator::NoteGenerator;
use contrapunk::harmony::{HarmonyEngine, HarmonyMode, Key, RoutingMode};
use contrapunk::humanize::HumanizeConfig;
use contrapunk::preset::PresetManager;

/// Application state managed by Tauri.
///
/// Wraps the core harmony engine, humanization config, preset manager,
/// and real-time note state in thread-safe containers for access from
/// both the main thread (command handlers) and the router thread.
pub struct AppState {
    /// Core harmony engine (key, mode, scale, voice leading, etc.)
    pub engine: Mutex<HarmonyEngine>,

    /// Humanization configuration
    pub humanize_config: Mutex<HumanizeConfig>,

    /// Preset manager for built-in and custom presets
    pub preset_manager: Mutex<PresetManager>,

    /// Whether MIDI routing is currently active
    pub is_running: AtomicBool,

    /// MIDI note numbers currently held on input (melody)
    pub input_notes: Mutex<HashSet<u8>>,

    /// MIDI note numbers generated by harmony engine
    pub harmony_notes: Mutex<HashSet<u8>>,

    /// MIDI note numbers borrowed from another mode via interchange
    pub borrowed_notes: Mutex<HashSet<u8>>,

    /// Currently detected chord name
    pub chord_name: Mutex<String>,

    /// Guitar input DSP configuration (None = use defaults)
    pub guitar_config: Mutex<Option<GuitarInputConfig>>,

    /// Guitar audio device name (empty = default input device)
    pub guitar_device: Mutex<String>,

    /// Guitar audio channel index (0-based, e.g. 0 = left, 1 = right)
    pub guitar_channel: Mutex<usize>,

    /// Note generator engine (arpeggio, scale runner, chord, etc.)
    pub generator: Mutex<NoteGenerator>,

    /// MIDI routing mode (channel-based MPE or port-based)
    pub routing_mode: Mutex<RoutingMode>,

    /// Stop signal for the router thread — set to true to stop the current routing
    pub stop_signal: Mutex<Option<Arc<AtomicBool>>>,

    /// Audio output engine (cpal stream lifecycle)
    pub audio_out: Mutex<AudioOutEngine>,

    /// MIDI producer for the audio output engine (None when engine is stopped)
    pub audio_out_producer: Mutex<Option<MidiProducer>>,

    /// Global detune in cents. Read by the router thread each frame (lock-free).
    /// Updated by the `set_detune` command.
    pub detune_cents: Arc<AtomicI32>,
}

impl Default for AppState {
    fn default() -> Self {
        Self {
            engine: Mutex::new(HarmonyEngine::new(Key::C, HarmonyMode::PassThrough)),
            humanize_config: Mutex::new(HumanizeConfig::default()),
            preset_manager: Mutex::new(PresetManager::new()),
            is_running: AtomicBool::new(false),
            input_notes: Mutex::new(HashSet::new()),
            harmony_notes: Mutex::new(HashSet::new()),
            borrowed_notes: Mutex::new(HashSet::new()),
            chord_name: Mutex::new(String::new()),
            guitar_config: Mutex::new(None),
            guitar_device: Mutex::new(String::new()),
            guitar_channel: Mutex::new(0),
            generator: Mutex::new(NoteGenerator::new()),
            routing_mode: Mutex::new(RoutingMode::default()),
            stop_signal: Mutex::new(None),
            audio_out: Mutex::new(AudioOutEngine::new()),
            audio_out_producer: Mutex::new(None),
            detune_cents: Arc::new(AtomicI32::new(0)),
        }
    }
}
