//! GUI application for Contrapunk MIDI harmony generator.
//!
//! This module provides the eframe/egui-based GUI interface.

use std::collections::HashSet;

use eframe::egui;

use crate::harmony::{Key, HarmonyMode};

/// Application state shared across the GUI.
///
/// Contains all the data needed to display and control the harmony engine.
pub struct AppState {
    /// Current musical key
    pub key: Key,
    /// Current harmony mode
    pub mode: HarmonyMode,
    /// MIDI note numbers currently held on input
    pub input_notes: HashSet<u8>,
    /// MIDI note numbers generated by harmony engine
    pub harmony_notes: HashSet<u8>,
    /// Selected input port index
    pub input_port: Option<usize>,
    /// Selected output port indices
    pub output_ports: Vec<usize>,
    /// Available input ports (index, name)
    pub available_inputs: Vec<(usize, String)>,
    /// Available output ports (index, name)
    pub available_outputs: Vec<(usize, String)>,
    /// Whether MIDI routing is active
    pub is_running: bool,
    /// Last error message for display
    pub last_error: Option<String>,
}

impl Default for AppState {
    fn default() -> Self {
        Self {
            key: Key::C,
            mode: HarmonyMode::PassThrough,
            input_notes: HashSet::new(),
            harmony_notes: HashSet::new(),
            input_port: None,
            output_ports: Vec::new(),
            available_inputs: Vec::new(),
            available_outputs: Vec::new(),
            is_running: false,
            last_error: None,
        }
    }
}

/// Main application struct for eframe.
pub struct ContrapunkApp {
    state: AppState,
}

impl ContrapunkApp {
    /// Create a new ContrapunkApp instance.
    pub fn new(_cc: &eframe::CreationContext<'_>) -> Self {
        Self {
            state: AppState::default(),
        }
    }
}

impl eframe::App for ContrapunkApp {
    fn update(&mut self, ctx: &egui::Context, _frame: &mut eframe::Frame) {
        egui::CentralPanel::default().show(ctx, |ui| {
            ui.vertical_centered(|ui| {
                ui.heading("Contrapunk");
                ui.add_space(10.0);
                ui.label("MIDI Harmony Generator");
            });

            ui.add_space(20.0);
            ui.separator();
            ui.add_space(10.0);

            // Current settings display
            ui.horizontal(|ui| {
                ui.label("Key:");
                ui.strong(format!("{}", self.state.key));
            });

            ui.horizontal(|ui| {
                ui.label("Mode:");
                ui.strong(format!("{} - {}",
                    self.state.mode.number(),
                    self.state.mode.description()
                ));
            });

            ui.add_space(20.0);
            ui.separator();
            ui.add_space(10.0);

            // Status display
            ui.horizontal(|ui| {
                ui.label("Status:");
                if self.state.is_running {
                    ui.colored_label(egui::Color32::GREEN, "Running");
                } else {
                    ui.colored_label(egui::Color32::GRAY, "Stopped");
                }
            });

            // Error display
            if let Some(ref error) = self.state.last_error {
                ui.add_space(10.0);
                ui.colored_label(egui::Color32::RED, format!("Error: {}", error));
            }

            ui.add_space(20.0);

            // Placeholder text
            ui.label("GUI controls will be added in subsequent plans.");
        });
    }
}
