//! Virtual piano keyboard widget for Contrapunk GUI.
//!
//! Displays a full 88-key piano keyboard (A0-C8) with color-coded keys showing
//! which notes are currently being played (input) and generated (harmony).
//! The keyboard scales to fill available width.
//! Supports click-to-select mode for the note generator.

use std::collections::HashSet;
use eframe::egui::{self, Color32, Pos2, Rect, Sense, Stroke, StrokeKind, Ui, Vec2};

/// MIDI note range for a standard 88-key piano.
const PIANO_START: u8 = 21;  // A0
const PIANO_END: u8 = 108;   // C8

/// Returns true if a MIDI note is a black key.
fn is_black_key(midi: u8) -> bool {
    matches!(midi % 12, 1 | 3 | 6 | 8 | 10)
}

/// Count white keys in the 88-key range (A0=21 to C8=108 inclusive).
fn count_white_keys() -> usize {
    (PIANO_START..=PIANO_END).filter(|&n| !is_black_key(n)).count()
}

/// Virtual piano keyboard widget.
///
/// Displays a piano keyboard with color-coded active notes:
/// - Blue: Input notes (what user is playing)
/// - Green: Harmony notes (generated by the engine)
/// - Cyan: Notes that are both input and harmony
/// - Magenta/accent: Generator-selected notes (click-to-select)
pub struct PianoKeyboard {
    /// Currently pressed input notes (MIDI numbers)
    input_notes: HashSet<u8>,
    /// Currently generated harmony notes (MIDI numbers)
    harmony_notes: HashSet<u8>,
    /// Generator-selected notes (MIDI numbers) for click-to-select highlight
    selected_notes: HashSet<u8>,
    /// Whether click-to-select mode is active (generator enabled)
    selectable: bool,
}

impl PianoKeyboard {
    /// Creates a new 88-key piano keyboard widget (A0-C8).
    pub fn new() -> Self {
        Self {
            input_notes: HashSet::new(),
            harmony_notes: HashSet::new(),
            selected_notes: HashSet::new(),
            selectable: false,
        }
    }

    /// Sets the input and harmony notes to highlight.
    pub fn with_notes(mut self, input: HashSet<u8>, harmony: HashSet<u8>) -> Self {
        self.input_notes = input;
        self.harmony_notes = harmony;
        self
    }

    /// Sets generator-selected notes and enables click-to-select mode.
    pub fn with_selectable(mut self, selected: HashSet<u8>, enabled: bool) -> Self {
        self.selected_notes = selected;
        self.selectable = enabled;
        self
    }

    /// Draws the piano keyboard in the UI, scaling to available width.
    /// Returns toggled notes (MIDI numbers) if any key was clicked in selectable mode.
    pub fn show(&self, ui: &mut Ui) -> Vec<u8> {
        let available_width = ui.available_width();
        let num_white = count_white_keys() as f32;
        let white_key_width = (available_width / num_white).max(8.0);
        let white_key_height = (white_key_width * 4.5).min(120.0);
        let black_key_width = white_key_width * 0.6;
        let black_key_height = white_key_height * 0.6;

        let total_width = num_white * white_key_width;

        let sense = if self.selectable { Sense::click() } else { Sense::hover() };
        let (response, painter) = ui.allocate_painter(
            Vec2::new(total_width, white_key_height),
            sense,
        );
        let rect = response.rect;

        // Draw white keys first (behind black keys)
        self.draw_white_keys(&painter, rect, white_key_width, white_key_height);

        // Draw black keys on top
        self.draw_black_keys(&painter, rect, white_key_width, black_key_width, black_key_height);

        // Handle clicks in selectable mode
        let mut toggled = Vec::new();
        if self.selectable {
            if let Some(click_pos) = response.interact_pointer_pos() {
                if response.clicked() {
                    // Check black keys first (they're on top)
                    if let Some(midi) = self.hit_test_black(rect, click_pos, white_key_width, black_key_width, black_key_height) {
                        toggled.push(midi);
                    } else if let Some(midi) = self.hit_test_white(rect, click_pos, white_key_width, white_key_height) {
                        toggled.push(midi);
                    }
                }
            }
        }
        toggled
    }

    /// Hit-test black keys. Returns MIDI note if click is on a black key.
    fn hit_test_black(&self, rect: Rect, pos: Pos2, white_width: f32, black_width: f32, black_height: f32) -> Option<u8> {
        let mut wi = 0;
        let mut white_positions: Vec<(u8, f32)> = Vec::new();
        for midi in PIANO_START..=PIANO_END {
            if !is_black_key(midi) {
                white_positions.push((midi, rect.left() + wi as f32 * white_width));
                wi += 1;
            }
        }
        for midi in PIANO_START..=PIANO_END {
            if !is_black_key(midi) { continue; }
            let prev_white = midi - 1;
            if let Some(&(_, px)) = white_positions.iter().find(|(n, _)| *n == prev_white) {
                let x = px + white_width - black_width / 2.0;
                let key_rect = Rect::from_min_size(egui::pos2(x, rect.top()), Vec2::new(black_width, black_height));
                if key_rect.contains(pos) {
                    return Some(midi);
                }
            }
        }
        None
    }

    /// Hit-test white keys. Returns MIDI note if click is on a white key.
    fn hit_test_white(&self, rect: Rect, pos: Pos2, key_width: f32, key_height: f32) -> Option<u8> {
        let mut white_index = 0;
        for midi in PIANO_START..=PIANO_END {
            if is_black_key(midi) { continue; }
            let x = rect.left() + white_index as f32 * key_width;
            let key_rect = Rect::from_min_size(Pos2::new(x, rect.top()), Vec2::new(key_width - 1.0, key_height));
            if key_rect.contains(pos) {
                return Some(midi);
            }
            white_index += 1;
        }
        None
    }

    /// Draws all white keys on the keyboard.
    fn draw_white_keys(&self, painter: &egui::Painter, rect: Rect, key_width: f32, key_height: f32) {
        let mut white_index = 0;
        for midi in PIANO_START..=PIANO_END {
            if is_black_key(midi) {
                continue;
            }
            let x = rect.left() + white_index as f32 * key_width;
            let key_rect = Rect::from_min_size(
                Pos2::new(x, rect.top()),
                Vec2::new(key_width - 1.0, key_height),
            );

            let color = self.key_color(midi, false);
            painter.rect_filled(key_rect, 2.0, color);
            painter.rect_stroke(key_rect, 2.0, Stroke::new(1.0, Color32::DARK_GRAY), StrokeKind::Inside);
            white_index += 1;
        }
    }

    /// Draws all black keys on the keyboard.
    fn draw_black_keys(&self, painter: &egui::Painter, rect: Rect, white_width: f32, black_width: f32, black_height: f32) {
        let mut white_x: Vec<(u8, f32)> = Vec::new();
        let mut wi = 0;
        for midi in PIANO_START..=PIANO_END {
            if !is_black_key(midi) {
                white_x.push((midi, rect.left() + wi as f32 * white_width));
                wi += 1;
            }
        }

        for midi in PIANO_START..=PIANO_END {
            if !is_black_key(midi) {
                continue;
            }
            let prev_white = midi - 1;
            if let Some(&(_, px)) = white_x.iter().find(|(n, _)| *n == prev_white) {
                let x = px + white_width - black_width / 2.0;
                let key_rect = Rect::from_min_size(
                    egui::pos2(x, rect.top()),
                    Vec2::new(black_width, black_height),
                );

                let color = self.key_color(midi, true);
                painter.rect_filled(key_rect, 2.0, color);
            }
        }
    }

    /// Returns the color for a key based on its active state.
    fn key_color(&self, midi: u8, is_black: bool) -> Color32 {
        let is_input = self.input_notes.contains(&midi);
        let is_harmony = self.harmony_notes.contains(&midi);
        let is_selected = self.selected_notes.contains(&midi);

        // Generator-selected notes get a distinct magenta/accent color
        if is_selected {
            return Color32::from_rgb(220, 50, 220); // Magenta - generator selected
        }

        match (is_input, is_harmony) {
            (true, true) => Color32::from_rgb(0, 200, 200),     // Cyan - both input and harmony
            (true, false) => Color32::from_rgb(100, 149, 237),  // Blue - input only
            (false, true) => Color32::from_rgb(50, 205, 50),    // Green - harmony only
            (false, false) => {
                if is_black {
                    Color32::from_rgb(30, 30, 30)     // Dark gray for black keys
                } else {
                    Color32::from_rgb(250, 250, 250) // White for white keys
                }
            }
        }
    }
}

impl Default for PianoKeyboard {
    fn default() -> Self {
        Self::new()
    }
}
