//! Virtual piano keyboard widget for Contrapunk GUI.
//!
//! Displays a 3-octave piano keyboard with color-coded keys showing
//! which notes are currently being played (input) and generated (harmony).

use std::collections::HashSet;
use eframe::egui::{self, Color32, Pos2, Rect, Sense, Stroke, StrokeKind, Ui, Vec2};

/// Virtual piano keyboard widget.
///
/// Displays a piano keyboard with color-coded active notes:
/// - Blue: Input notes (what user is playing)
/// - Green: Harmony notes (generated by the engine)
/// - Cyan: Notes that are both input and harmony
pub struct PianoKeyboard {
    /// Starting MIDI note (e.g., 48 for C3)
    start_note: u8,
    /// Number of octaves to display
    octaves: u8,
    /// Currently pressed input notes (MIDI numbers)
    input_notes: HashSet<u8>,
    /// Currently generated harmony notes (MIDI numbers)
    harmony_notes: HashSet<u8>,
}

impl PianoKeyboard {
    /// Creates a new piano keyboard widget.
    ///
    /// Default configuration: 3 octaves starting at C3 (MIDI 48).
    pub fn new() -> Self {
        Self {
            start_note: 48,  // C3
            octaves: 3,      // C3 to B5 (36 keys)
            input_notes: HashSet::new(),
            harmony_notes: HashSet::new(),
        }
    }

    /// Sets the input and harmony notes to highlight.
    pub fn with_notes(mut self, input: HashSet<u8>, harmony: HashSet<u8>) -> Self {
        self.input_notes = input;
        self.harmony_notes = harmony;
        self
    }

    /// Draws the piano keyboard in the UI.
    pub fn show(&self, ui: &mut Ui) {
        let white_key_width = 24.0;
        let white_key_height = 100.0;
        let black_key_width = 14.0;
        let black_key_height = 60.0;

        // Calculate total width (7 white keys per octave)
        let total_white_keys = self.octaves as usize * 7;
        let total_width = total_white_keys as f32 * white_key_width;

        let (response, painter) = ui.allocate_painter(
            Vec2::new(total_width, white_key_height),
            Sense::hover(),
        );
        let rect = response.rect;

        // Draw white keys first (they're behind black keys)
        self.draw_white_keys(&painter, rect, white_key_width, white_key_height);

        // Draw black keys on top
        self.draw_black_keys(&painter, rect, white_key_width, black_key_width, black_key_height);
    }

    /// Draws all white keys on the keyboard.
    fn draw_white_keys(&self, painter: &egui::Painter, rect: Rect, key_width: f32, key_height: f32) {
        // White key chromatic offsets: C=0, D=2, E=4, F=5, G=7, A=9, B=11
        let white_key_offsets = [0, 2, 4, 5, 7, 9, 11];

        for octave in 0..self.octaves as usize {
            for (i, &offset) in white_key_offsets.iter().enumerate() {
                let midi = self.start_note + (octave as u8 * 12) + offset;
                let x = rect.left() + (octave * 7 + i) as f32 * key_width;

                let key_rect = Rect::from_min_size(
                    Pos2::new(x, rect.top()),
                    Vec2::new(key_width - 1.0, key_height),
                );

                let color = self.key_color(midi, false);
                painter.rect_filled(key_rect, 2.0, color);
                painter.rect_stroke(key_rect, 2.0, Stroke::new(1.0, Color32::DARK_GRAY), StrokeKind::Inside);
            }
        }
    }

    /// Draws all black keys on the keyboard.
    fn draw_black_keys(&self, painter: &egui::Painter, rect: Rect, white_width: f32, black_width: f32, black_height: f32) {
        // Black keys: C#=1, D#=3, F#=6, G#=8, A#=10
        // They sit between white keys at positions: after C(0), D(1), F(3), G(4), A(5)
        let black_positions = [
            (0, 1),   // C# after C (white key index 0)
            (1, 3),   // D# after D (white key index 1)
            (3, 6),   // F# after F (white key index 3)
            (4, 8),   // G# after G (white key index 4)
            (5, 10),  // A# after A (white key index 5)
        ];

        for octave in 0..self.octaves as usize {
            for &(white_idx, offset) in &black_positions {
                let midi = self.start_note + (octave as u8 * 12) + offset;
                let x = rect.left() + (octave * 7 + white_idx) as f32 * white_width + white_width - black_width / 2.0;

                let key_rect = Rect::from_min_size(
                    egui::pos2(x, rect.top()),
                    Vec2::new(black_width, black_height),
                );

                let color = self.key_color(midi, true);
                painter.rect_filled(key_rect, 2.0, color);
            }
        }
    }

    /// Returns the color for a key based on its active state.
    fn key_color(&self, midi: u8, is_black: bool) -> Color32 {
        let is_input = self.input_notes.contains(&midi);
        let is_harmony = self.harmony_notes.contains(&midi);

        match (is_input, is_harmony) {
            (true, true) => Color32::from_rgb(0, 200, 200),     // Cyan - both input and harmony
            (true, false) => Color32::from_rgb(100, 149, 237),  // Blue - input only
            (false, true) => Color32::from_rgb(50, 205, 50),    // Green - harmony only
            (false, false) => {
                if is_black {
                    Color32::from_rgb(30, 30, 30)     // Dark gray for black keys
                } else {
                    Color32::from_rgb(250, 250, 250) // White for white keys
                }
            }
        }
    }
}

impl Default for PianoKeyboard {
    fn default() -> Self {
        Self::new()
    }
}
