//! MIDI message routing from input to outputs with harmony generation.
//!
//! Provides the main routing loop that connects MIDI input to outputs
//! and processes messages through the HarmonyEngine.

#[cfg(feature = "gui")]
use crate::harmony::{HarmonyEngine, Key, HarmonyMode, OctaveMode};
#[cfg(not(feature = "gui"))]
use crate::harmony::HarmonyEngine;
use crate::midi::input::connect_input;
use crate::midi::output::OutputRouter;
use anyhow::Result;
#[cfg(feature = "gui")]
use std::collections::HashSet;
#[cfg(not(feature = "gui"))]
use std::io::{self, BufRead};
#[cfg(feature = "gui")]
use std::sync::{Arc, Mutex};
use std::sync::mpsc;
#[cfg(feature = "gui")]
use std::thread::{self, JoinHandle};
#[cfg(not(feature = "gui"))]
use std::thread;
use std::time::Duration;
use wmidi::{Channel, MidiMessage, Note, Velocity};

#[cfg(feature = "gui")]
use eframe::egui;

/// Shared state for GUI router communication.
///
/// Allows the GUI to observe router state and control the router.
#[cfg(feature = "gui")]
#[derive(Default)]
pub struct GUIRouterState {
    /// MIDI note numbers currently held on input
    pub input_notes: HashSet<u8>,
    /// MIDI note numbers generated by harmony engine (on all outputs)
    pub harmony_notes: HashSet<u8>,
    /// Signal to stop the router thread
    pub stop_signal: bool,
}

/// Spawns the MIDI router in a background thread for GUI mode.
///
/// # Arguments
///
/// * `input_port` - Index of the MIDI input port
/// * `output_ports` - Vec of output port indices
/// * `key` - Initial musical key
/// * `mode` - Initial harmony mode
/// * `octave_mode` - Octave placement mode for harmony voices
/// * `state` - Shared state for GUI communication
/// * `ctx` - egui context for requesting repaints
///
/// # Returns
///
/// Returns a JoinHandle to the spawned thread, or an error if connection fails.
#[cfg(feature = "gui")]
pub fn spawn_gui_router(
    input_port: usize,
    output_ports: Vec<usize>,
    key: Key,
    mode: HarmonyMode,
    octave_mode: OctaveMode,
    state: Arc<Mutex<GUIRouterState>>,
    ctx: egui::Context,
) -> Result<JoinHandle<Result<()>>> {
    // Validate parameters before spawning thread
    if output_ports.is_empty() {
        return Err(anyhow::anyhow!("At least one output port required"));
    }

    let handle = thread::spawn(move || -> Result<()> {
        run_gui_router_inner(input_port, &output_ports, key, mode, octave_mode, state, ctx)
    });

    Ok(handle)
}

/// Inner function that runs the GUI router loop.
#[cfg(feature = "gui")]
fn run_gui_router_inner(
    input_port: usize,
    output_ports: &[usize],
    key: Key,
    mode: HarmonyMode,
    octave_mode: OctaveMode,
    state: Arc<Mutex<GUIRouterState>>,
    ctx: egui::Context,
) -> Result<()> {
    // Create channel for message forwarding from input callback to main loop
    let (tx, rx) = mpsc::channel::<Vec<u8>>();

    // Connect to input port - IMPORTANT: Must keep connection alive
    let _conn_in = connect_input(input_port, tx)?;

    // Create output router
    let mut output_router = OutputRouter::new(output_ports)?;

    // Create harmony engine
    let mut engine = HarmonyEngine::new(key, mode);
    let num_outputs = output_router.connection_count();
    engine.set_voice_count(num_outputs);
    engine.set_octave_mode(octave_mode);

    // Main routing loop
    loop {
        // Check stop signal
        {
            let state_lock = state.lock().unwrap();
            if state_lock.stop_signal {
                break;
            }
        }

        // Try to receive MIDI message with short timeout
        match rx.recv_timeout(Duration::from_millis(50)) {
            Ok(message) => {
                if let Err(e) = process_midi_message_gui(&message, &mut engine, &mut output_router, &state) {
                    eprintln!("Error processing message: {}", e);
                }
                // Request GUI repaint to show updated notes
                ctx.request_repaint();
            }
            Err(mpsc::RecvTimeoutError::Timeout) => {
                // No message received, continue loop
            }
            Err(mpsc::RecvTimeoutError::Disconnected) => {
                eprintln!("Input channel disconnected unexpectedly.");
                break;
            }
        }
    }

    // Clear note state on exit
    {
        let mut state_lock = state.lock().unwrap();
        state_lock.input_notes.clear();
        state_lock.harmony_notes.clear();
    }
    ctx.request_repaint();

    Ok(())
}

/// Processes a single MIDI message for GUI mode (updates shared state).
#[cfg(feature = "gui")]
fn process_midi_message_gui(
    bytes: &[u8],
    engine: &mut HarmonyEngine,
    output: &mut OutputRouter,
    state: &Arc<Mutex<GUIRouterState>>,
) -> Result<()> {
    // Try to parse as MIDI message
    let msg = match MidiMessage::try_from(bytes) {
        Ok(m) => m,
        Err(_) => {
            // Unknown message, pass through to first output
            output.send_to_first(bytes)?;
            return Ok(());
        }
    };

    match msg {
        MidiMessage::NoteOn(channel, note, velocity) => {
            if velocity == Velocity::MIN {
                // Velocity 0 = Note-Off (running status optimization)
                handle_note_off_gui(channel, note, velocity, engine, output, state)?;
            } else {
                handle_note_on_gui(channel, note, velocity, engine, output, state)?;
            }
        }
        MidiMessage::NoteOff(channel, note, velocity) => {
            handle_note_off_gui(channel, note, velocity, engine, output, state)?;
        }
        _ => {
            // Non-note messages: pass through unchanged to first output
            output.send_to_first(bytes)?;
        }
    }

    Ok(())
}

/// Handles Note-On for GUI mode: harmonize, send to outputs, update state.
#[cfg(feature = "gui")]
fn handle_note_on_gui(
    channel: Channel,
    note: Note,
    velocity: Velocity,
    engine: &mut HarmonyEngine,
    output: &mut OutputRouter,
    state: &Arc<Mutex<GUIRouterState>>,
) -> Result<()> {
    let notes = engine.harmonize_note_on(note);
    let num_outputs = output.connection_count();

    // Update shared state with active notes
    // Note: notes[0] is melody (same as input), notes[1..] are harmonies
    {
        let mut state_lock = state.lock().unwrap();
        state_lock.input_notes.insert(note as u8);
        // Skip first note (melody) - only add harmony notes
        for &n in notes.iter().skip(1) {
            state_lock.harmony_notes.insert(n as u8);
        }
    }

    // Send each note to its corresponding output port
    for (i, &n) in notes.iter().enumerate() {
        if i < num_outputs {
            let msg = MidiMessage::NoteOn(channel, n, velocity);
            let mut buf = vec![0u8; msg.bytes_size()];
            msg.copy_to_slice(&mut buf)?;
            output.send_to_port(i, &buf)?;
        }
    }

    Ok(())
}

/// Handles Note-Off for GUI mode: release notes, update state.
#[cfg(feature = "gui")]
fn handle_note_off_gui(
    channel: Channel,
    note: Note,
    velocity: Velocity,
    engine: &mut HarmonyEngine,
    output: &mut OutputRouter,
    state: &Arc<Mutex<GUIRouterState>>,
) -> Result<()> {
    let notes = engine.harmonize_note_off(note);
    let num_outputs = output.connection_count();

    // Update shared state - remove released notes
    // Note: notes[0] is melody (same as input), notes[1..] are harmonies
    {
        let mut state_lock = state.lock().unwrap();
        state_lock.input_notes.remove(&(note as u8));
        // Skip first note (melody) - only remove harmony notes
        for &n in notes.iter().skip(1) {
            state_lock.harmony_notes.remove(&(n as u8));
        }
    }

    // Release each note on its corresponding output port
    for (i, &n) in notes.iter().enumerate() {
        if i < num_outputs {
            let msg = MidiMessage::NoteOff(channel, n, velocity);
            let mut buf = vec![0u8; msg.bytes_size()];
            msg.copy_to_slice(&mut buf)?;
            output.send_to_port(i, &buf)?;
        }
    }

    Ok(())
}

// ============================================================================
// CLI-mode router (non-GUI)
// ============================================================================

/// Runs the MIDI routing loop with harmony generation (CLI mode).
///
/// Connects to the specified input port and output ports, then enters
/// a loop that processes MIDI messages through the HarmonyEngine.
///
/// - Original notes go to output port 0
/// - Chained harmonies go to ports 1, 2, 3, ... (one per port)
///   - Harmony 1 (of melody) -> port 1
///   - Harmony 2 (of harmony 1) -> port 2
///   - Harmony 3 (of harmony 2) -> port 3
/// - Non-note messages pass through to first output
///
/// # Arguments
///
/// * `input_port` - Index of the MIDI input port
/// * `output_ports` - Slice of output port indices
/// * `engine` - HarmonyEngine configured with key and mode
///
/// # Returns
///
/// Returns `Ok(())` when the user exits, or an error if connection fails.
#[cfg(not(feature = "gui"))]
pub fn run_router(
    input_port: usize,
    output_ports: &[usize],
    engine: &mut HarmonyEngine,
) -> Result<()> {
    // Create channel for message forwarding from input callback to main loop
    let (tx, rx) = mpsc::channel::<Vec<u8>>();

    // Connect to input port - IMPORTANT: Must keep connection alive
    let _conn_in = connect_input(input_port, tx)?;

    // Create output router
    let mut output_router = OutputRouter::new(output_ports)?;

    // Configure engine voice count to match output count
    let num_outputs = output_router.connection_count();
    engine.set_voice_count(num_outputs);

    println!("\n========================================");
    println!("MIDI harmony routing active.");
    println!(
        "Key: {:?}, Mode: {} - {}",
        engine.key(),
        engine.mode().number(),
        engine.mode().description()
    );
    println!("Voices: {} (melody + {} chained harmonies)", num_outputs, num_outputs.saturating_sub(1));
    println!("Press Enter to stop.");
    println!("========================================\n");

    // Create a channel to signal when Enter is pressed
    let (stop_tx, stop_rx) = mpsc::channel::<()>();

    // Spawn thread to wait for Enter key
    thread::spawn(move || {
        let stdin = io::stdin();
        let mut handle = stdin.lock();
        let mut line = String::new();
        let _ = handle.read_line(&mut line);
        let _ = stop_tx.send(());
    });

    // Main routing loop
    loop {
        // Check if user pressed Enter (non-blocking)
        if stop_rx.try_recv().is_ok() {
            println!("\nStopping MIDI router...");
            break;
        }

        // Try to receive MIDI message with timeout
        match rx.recv_timeout(Duration::from_millis(100)) {
            Ok(message) => {
                if let Err(e) = process_midi_message(&message, engine, &mut output_router) {
                    eprintln!("Error processing message: {}", e);
                }
            }
            Err(mpsc::RecvTimeoutError::Timeout) => {
                // No message received, continue loop (allows checking for Enter)
            }
            Err(mpsc::RecvTimeoutError::Disconnected) => {
                eprintln!("Input channel disconnected unexpectedly.");
                break;
            }
        }
    }

    println!("MIDI router stopped.");
    Ok(())
}

/// Processes a single MIDI message through the harmony engine (CLI mode).
#[cfg(not(feature = "gui"))]
fn process_midi_message(
    bytes: &[u8],
    engine: &mut HarmonyEngine,
    output: &mut OutputRouter,
) -> Result<()> {
    // Try to parse as MIDI message
    let msg = match MidiMessage::try_from(bytes) {
        Ok(m) => m,
        Err(_) => {
            // Unknown message, pass through to first output
            output.send_to_first(bytes)?;
            return Ok(());
        }
    };

    match msg {
        MidiMessage::NoteOn(channel, note, velocity) => {
            if velocity == Velocity::MIN {
                // Velocity 0 = Note-Off (running status optimization)
                handle_note_off(channel, note, velocity, engine, output)?;
            } else {
                handle_note_on(channel, note, velocity, engine, output)?;
            }
        }
        MidiMessage::NoteOff(channel, note, velocity) => {
            handle_note_off(channel, note, velocity, engine, output)?;
        }
        _ => {
            // Non-note messages: pass through unchanged to first output
            output.send_to_first(bytes)?;
        }
    }

    Ok(())
}

/// Handles Note-On: harmonize and send to outputs (CLI mode).
#[cfg(not(feature = "gui"))]
fn handle_note_on(
    channel: Channel,
    note: Note,
    velocity: Velocity,
    engine: &mut HarmonyEngine,
    output: &mut OutputRouter,
) -> Result<()> {
    let notes = engine.harmonize_note_on(note);
    let num_outputs = output.connection_count();

    // Send each note to its corresponding output port
    // note[0] -> port 0 (melody)
    // note[1] -> port 1 (harmony of melody)
    // note[2] -> port 2 (harmony of harmony 1)
    // etc.
    for (i, &n) in notes.iter().enumerate() {
        if i < num_outputs {
            let msg = MidiMessage::NoteOn(channel, n, velocity);
            let mut buf = vec![0u8; msg.bytes_size()];
            msg.copy_to_slice(&mut buf)?;
            output.send_to_port(i, &buf)?;
        }
    }

    // Debug output
    if notes.len() > 1 {
        let note_strs: Vec<String> = notes.iter()
            .enumerate()
            .map(|(i, n)| format!("{:?}->p{}", n, i))
            .collect();
        println!("[CHAIN] {:?} => [{}]", note, note_strs.join(", "));
    } else {
        println!("[PASS] {:?}", note);
    }

    Ok(())
}

/// Handles Note-Off: release original and harmony notes (CLI mode).
#[cfg(not(feature = "gui"))]
fn handle_note_off(
    channel: Channel,
    note: Note,
    velocity: Velocity,
    engine: &mut HarmonyEngine,
    output: &mut OutputRouter,
) -> Result<()> {
    let notes = engine.harmonize_note_off(note);
    let num_outputs = output.connection_count();

    // Release each note on its corresponding output port
    for (i, &n) in notes.iter().enumerate() {
        if i < num_outputs {
            let msg = MidiMessage::NoteOff(channel, n, velocity);
            let mut buf = vec![0u8; msg.bytes_size()];
            msg.copy_to_slice(&mut buf)?;
            output.send_to_port(i, &buf)?;
        }
    }

    Ok(())
}
