//! MIDI message routing from input to outputs with harmony generation.
//!
//! Provides the main routing loop that connects MIDI input to outputs
//! and processes messages through the HarmonyEngine.

#[cfg(feature = "gui")]
use crate::harmony::{HarmonyEngine, Key, HarmonyMode, OctaveMode, VoiceLeadingStyle};
#[cfg(not(feature = "gui"))]
use crate::harmony::HarmonyEngine;
#[cfg(feature = "gui")]
use crate::generator::{NoteGenerator, GeneratorMode, GeneratorEvent};
use crate::humanize::{DelayQueue, HumanizeConfig, HumanizedNote, Humanizer, Metronome};
use crate::midi::input::connect_input;
use crate::midi::output::OutputRouter;
use anyhow::Result;
#[cfg(feature = "gui")]
use std::collections::HashSet;
#[cfg(not(feature = "gui"))]
use std::io::{self, BufRead};
#[cfg(feature = "gui")]
use std::sync::{Arc, Mutex};
use std::sync::mpsc;
#[cfg(feature = "gui")]
use std::thread::{self, JoinHandle};
#[cfg(not(feature = "gui"))]
use std::thread;
use std::time::{Duration, Instant};
use wmidi::{Channel, MidiMessage, Note, Velocity};

#[cfg(feature = "gui")]
use eframe::egui;

/// Shared state for GUI router communication.
///
/// Allows the GUI to observe router state and control the router.
#[cfg(feature = "gui")]
pub struct GUIRouterState {
    /// MIDI note numbers currently held on input
    pub input_notes: HashSet<u8>,
    /// MIDI note numbers generated by harmony engine (on all outputs)
    pub harmony_notes: HashSet<u8>,
    /// Signal to stop the router thread
    pub stop_signal: bool,
    /// Humanization configuration (GUI can read/write)
    pub humanize_config: HumanizeConfig,
    /// Whether voice leading is enabled
    pub voice_leading_enabled: bool,
    /// Current voice leading style
    pub voice_leading_style: VoiceLeadingStyle,
    /// Current musical key (synced from GUI)
    pub key: Option<Key>,
    /// Current harmony mode (synced from GUI)
    pub mode: Option<HarmonyMode>,
    /// Current octave mode (synced from GUI)
    pub octave_mode: Option<OctaveMode>,
    /// Whether the note generator is enabled
    pub generator_enabled: bool,
    /// Generator mode (taken by router when changed)
    pub generator_mode: Option<GeneratorMode>,
    /// Generator selected notes (taken by router when changed)
    pub generator_selected_notes: Option<Vec<wmidi::Note>>,
    /// Generator velocity
    pub generator_velocity: u8,
    /// Generator note duration in beats
    pub generator_note_duration_beats: f64,
    /// Keyboard input events: (is_note_on, note)
    pub keyboard_events: Vec<(bool, wmidi::Note)>,
    /// Whether keyboard input is enabled
    pub keyboard_enabled: bool,
}

#[cfg(feature = "gui")]
impl Default for GUIRouterState {
    fn default() -> Self {
        Self {
            input_notes: HashSet::new(),
            harmony_notes: HashSet::new(),
            stop_signal: false,
            humanize_config: HumanizeConfig::default(),
            voice_leading_enabled: false,
            voice_leading_style: VoiceLeadingStyle::default(),
            key: None,
            mode: None,
            octave_mode: None,
            generator_enabled: false,
            generator_mode: None,
            generator_selected_notes: None,
            generator_velocity: 100,
            generator_note_duration_beats: 0.5,
            keyboard_events: Vec::new(),
            keyboard_enabled: false,
        }
    }
}

/// Spawns the MIDI router in a background thread for GUI mode.
#[cfg(feature = "gui")]
pub fn spawn_gui_router(
    input_port: usize,
    output_ports: Vec<usize>,
    key: Key,
    mode: HarmonyMode,
    octave_mode: OctaveMode,
    state: Arc<Mutex<GUIRouterState>>,
    ctx: egui::Context,
) -> Result<JoinHandle<Result<()>>> {
    // Validate parameters before spawning thread
    if output_ports.is_empty() {
        return Err(anyhow::anyhow!("At least one output port required"));
    }

    let handle = thread::spawn(move || -> Result<()> {
        run_gui_router_inner(input_port, &output_ports, key, mode, octave_mode, state, ctx)
    });

    Ok(handle)
}

/// Inner function that runs the GUI router loop.
#[cfg(feature = "gui")]
fn run_gui_router_inner(
    input_port: usize,
    output_ports: &[usize],
    key: Key,
    mode: HarmonyMode,
    octave_mode: OctaveMode,
    state: Arc<Mutex<GUIRouterState>>,
    ctx: egui::Context,
) -> Result<()> {
    // Create channel for message forwarding from input callback to main loop
    let (tx, rx) = mpsc::channel::<Vec<u8>>();

    // Connect to input port - IMPORTANT: Must keep connection alive
    // Virtual inputs (usize::MAX, usize::MAX-1) don't need physical connection
    let _conn_in = if input_port < usize::MAX - 1 {
        Some(connect_input(input_port, tx)?)
    } else {
        None
    };

    // Create output router
    let mut output_router = OutputRouter::new(output_ports)?;

    // Create harmony engine
    let mut engine = HarmonyEngine::new(key, mode);
    let num_outputs = output_router.connection_count();
    engine.set_voice_count(num_outputs);
    engine.set_octave_mode(octave_mode);

    // Create humanizer, delay queue, and metronome
    let mut humanizer = Humanizer::new(HumanizeConfig::default());
    let mut delay_queue = DelayQueue::new();
    let metronome = Metronome::new();
    let epoch = Instant::now();
    let now_ms = || epoch.elapsed().as_secs_f64() * 1000.0;

    // Create note generator (owned by router thread)
    let mut generator = NoteGenerator::new();

    // Start the beat clock
    humanizer.clock_mut().start(now_ms());

    // Main routing loop
    loop {
        // Check stop signal
        {
            let state_lock = state.lock().unwrap();
            if state_lock.stop_signal {
                break;
            }
        }

        // Tick humanizer clock
        let current_ms = now_ms();
        humanizer.tick(current_ms);

        // Sync humanizer config, voice leading, and key/mode/octave from shared state
        {
            let mut state_lock = state.lock().unwrap();
            humanizer.update_config(state_lock.humanize_config.clone());
            if engine.voice_leading_enabled() != state_lock.voice_leading_enabled {
                engine.set_voice_leading_enabled(state_lock.voice_leading_enabled);
            }
            if engine.voice_leading_style() != state_lock.voice_leading_style {
                engine.set_voice_leading_style(state_lock.voice_leading_style);
            }
            // Sync key/mode/octave if changed from GUI
            if let Some(new_key) = state_lock.key.take() {
                if engine.key() != new_key {
                    engine.set_key(new_key);
                }
            }
            if let Some(new_mode) = state_lock.mode.take() {
                if engine.mode() != new_mode {
                    engine.set_mode(new_mode);
                }
            }
            if let Some(new_octave) = state_lock.octave_mode.take() {
                engine.set_octave_mode(new_octave);
            }

            // Sync generator config from GUI — collect pending events, process after lock drop
            let mut pending_gen_events: Vec<GeneratorEvent> = Vec::new();
            let gen_enabled = state_lock.generator_enabled;
            if generator.enabled() != gen_enabled {
                pending_gen_events.extend(generator.set_enabled(gen_enabled));
            }
            if let Some(new_mode) = state_lock.generator_mode.take() {
                pending_gen_events.extend(generator.set_mode(new_mode));
            }
            if let Some(new_notes) = state_lock.generator_selected_notes.take() {
                pending_gen_events.extend(generator.set_selected_notes(new_notes));
            }
            generator.set_velocity(state_lock.generator_velocity);
            generator.set_note_duration_beats(state_lock.generator_note_duration_beats);

            // Drain keyboard events
            let kbd_events: Vec<(bool, Note)> = state_lock.keyboard_events.drain(..).collect();
            drop(state_lock);

            // Process pending generator note-off events
            for event in pending_gen_events {
                if let GeneratorEvent::NoteOff(note) = event {
                    let _ = handle_note_off_gui(
                        Channel::Ch1, note, Velocity::try_from(0u8).unwrap(),
                        &mut engine, &mut output_router, &state, &mut humanizer, &mut delay_queue, current_ms,
                    );
                }
            }

            // Process keyboard events through harmony pipeline
            for (is_on, note) in kbd_events {
                if is_on {
                    let _ = handle_note_on_gui(
                        Channel::Ch1, note, Velocity::try_from(100u8).unwrap(),
                        &mut engine, &mut output_router, &state, &mut humanizer, &mut delay_queue, current_ms,
                    );
                } else {
                    let _ = handle_note_off_gui(
                        Channel::Ch1, note, Velocity::try_from(0u8).unwrap(),
                        &mut engine, &mut output_router, &state, &mut humanizer, &mut delay_queue, current_ms,
                    );
                }
            }
        }

        // Tick generator and process events through harmony pipeline
        if generator.enabled() {
            let beat_pos = humanizer.clock().beat_position();
            let bpm = humanizer.config().bpm;
            let gen_events = generator.tick(beat_pos, bpm);
            let current_ms = now_ms();
            for event in gen_events {
                match event {
                    GeneratorEvent::NoteOn(note, vel) => {
                        let velocity = Velocity::try_from(vel).unwrap_or(Velocity::MAX);
                        let _ = handle_note_on_gui(
                            Channel::Ch1, note, velocity,
                            &mut engine, &mut output_router, &state, &mut humanizer, &mut delay_queue, current_ms,
                        );
                    }
                    GeneratorEvent::NoteOff(note) => {
                        let _ = handle_note_off_gui(
                            Channel::Ch1, note, Velocity::try_from(0u8).unwrap(),
                            &mut engine, &mut output_router, &state, &mut humanizer, &mut delay_queue, current_ms,
                        );
                    }
                }
            }
            ctx.request_repaint();
        }

        // Check metronome: generate click on beat crossings
        if humanizer.config().metronome_enabled {
            if let Some(beat) = humanizer.clock().beat_crossed() {
                let metro_port = humanizer.config().metronome_output_port.unwrap_or(0);
                let click = metronome.generate_click(beat);
                let _ = output_router.send_to_port(metro_port, &click);
                // Schedule click-off after 50ms
                let click_off_note = HumanizedNote {
                    note: if beat == 0 {
                        Note::try_from(76u8).unwrap()
                    } else {
                        Note::try_from(77u8).unwrap()
                    },
                    channel: Channel::Ch10,
                    velocity: Velocity::try_from(0u8).unwrap(),
                    delay_ms: 50,
                    duration_delta_ms: 0,
                    port: metro_port,
                    is_note_off: true,
                };
                delay_queue.push(click_off_note, current_ms);
            }
        }

        // Drain delay queue: send all ready notes
        let current_ms = now_ms();
        for hn in delay_queue.drain_ready(current_ms) {
            let _ = send_humanized_note(&hn, &mut output_router);
        }

        // Try to receive MIDI message with short timeout
        match rx.recv_timeout(Duration::from_millis(5)) {
            Ok(message) => {
                let current_ms = now_ms();
                if let Err(e) = process_midi_message_gui(
                    &message,
                    &mut engine,
                    &mut output_router,
                    &state,
                    &mut humanizer,
                    &mut delay_queue,
                    current_ms,
                ) {
                    eprintln!("Error processing message: {}", e);
                }
                // Request GUI repaint to show updated notes
                ctx.request_repaint();
            }
            Err(mpsc::RecvTimeoutError::Timeout) => {
                // No message received, continue loop
            }
            Err(mpsc::RecvTimeoutError::Disconnected) => {
                eprintln!("Input channel disconnected unexpectedly.");
                break;
            }
        }
    }

    // Clear note state on exit
    {
        let mut state_lock = state.lock().unwrap();
        state_lock.input_notes.clear();
        state_lock.harmony_notes.clear();
    }
    ctx.request_repaint();

    Ok(())
}

/// Sends a humanized note to the appropriate output port.
fn send_humanized_note(note: &HumanizedNote, output: &mut OutputRouter) -> Result<()> {
    let msg = if note.is_note_off {
        MidiMessage::NoteOff(note.channel, note.note, note.velocity)
    } else {
        MidiMessage::NoteOn(note.channel, note.note, note.velocity)
    };
    let mut buf = vec![0u8; msg.bytes_size()];
    msg.copy_to_slice(&mut buf)?;
    output.send_to_port(note.port, &buf)?;
    Ok(())
}

/// Processes a single MIDI message for GUI mode (updates shared state).
#[cfg(feature = "gui")]
fn process_midi_message_gui(
    bytes: &[u8],
    engine: &mut HarmonyEngine,
    output: &mut OutputRouter,
    state: &Arc<Mutex<GUIRouterState>>,
    humanizer: &mut Humanizer,
    delay_queue: &mut DelayQueue,
    now_ms: f64,
) -> Result<()> {
    // Try to parse as MIDI message
    let msg = match MidiMessage::try_from(bytes) {
        Ok(m) => m,
        Err(_) => {
            // Unknown message, pass through to first output
            output.send_to_first(bytes)?;
            return Ok(());
        }
    };

    match msg {
        MidiMessage::NoteOn(channel, note, velocity) => {
            if velocity == Velocity::MIN {
                handle_note_off_gui(channel, note, velocity, engine, output, state, humanizer, delay_queue, now_ms)?;
            } else {
                handle_note_on_gui(channel, note, velocity, engine, output, state, humanizer, delay_queue, now_ms)?;
            }
        }
        MidiMessage::NoteOff(channel, note, velocity) => {
            handle_note_off_gui(channel, note, velocity, engine, output, state, humanizer, delay_queue, now_ms)?;
        }
        _ => {
            // Non-note messages: pass through unchanged to first output
            output.send_to_first(bytes)?;
        }
    }

    Ok(())
}

/// Handles Note-On for GUI mode: harmonize, humanize harmony notes, send to outputs.
#[cfg(feature = "gui")]
fn handle_note_on_gui(
    channel: Channel,
    note: Note,
    velocity: Velocity,
    engine: &mut HarmonyEngine,
    output: &mut OutputRouter,
    state: &Arc<Mutex<GUIRouterState>>,
    humanizer: &mut Humanizer,
    delay_queue: &mut DelayQueue,
    now_ms: f64,
) -> Result<()> {
    let notes = engine.harmonize_note_on(note);
    let num_outputs = output.connection_count();

    // Update shared state with active notes
    {
        let mut state_lock = state.lock().unwrap();
        state_lock.input_notes.insert(note as u8);
        for &n in notes.iter().skip(1) {
            state_lock.harmony_notes.insert(n as u8);
        }
    }

    // Skip metronome-dedicated port for harmony/melody notes
    let metro_reserved = if humanizer.config().metronome_enabled {
        humanizer.config().metronome_output_port
    } else {
        None
    };

    // Send each note to its port
    let port_map = engine.last_port_map();
    for (i, &n) in notes.iter().enumerate() {
        let port = if i < port_map.len() { port_map[i] } else { i };
        if port >= num_outputs || Some(port) == metro_reserved {
            continue;
        }

        if i == 0 {
            // Melody (index 0): send immediately, no humanization
            let msg = MidiMessage::NoteOn(channel, n, velocity);
            let mut buf = vec![0u8; msg.bytes_size()];
            msg.copy_to_slice(&mut buf)?;
            output.send_to_port(port, &buf)?;
        } else {
            // Harmony (index 1+): humanize
            let hn = humanizer.humanize_note_on(n, channel, velocity, port);
            if hn.delay_ms == 0 {
                send_humanized_note(&hn, output)?;
            } else {
                delay_queue.push(hn, now_ms);
            }
        }
    }

    Ok(())
}

/// Handles Note-Off for GUI mode: release notes, humanize harmony note-offs.
#[cfg(feature = "gui")]
fn handle_note_off_gui(
    channel: Channel,
    note: Note,
    velocity: Velocity,
    engine: &mut HarmonyEngine,
    output: &mut OutputRouter,
    state: &Arc<Mutex<GUIRouterState>>,
    humanizer: &mut Humanizer,
    delay_queue: &mut DelayQueue,
    now_ms: f64,
) -> Result<()> {
    let notes = engine.harmonize_note_off(note);
    let num_outputs = output.connection_count();

    // Update shared state - remove released notes
    {
        let mut state_lock = state.lock().unwrap();
        state_lock.input_notes.remove(&(note as u8));
        for &n in notes.iter().skip(1) {
            state_lock.harmony_notes.remove(&(n as u8));
        }
    }

    // Skip metronome-dedicated port for harmony/melody notes
    let metro_reserved = if humanizer.config().metronome_enabled {
        humanizer.config().metronome_output_port
    } else {
        None
    };

    // Release each note on its port
    let port_map = engine.last_port_map();
    for (i, &n) in notes.iter().enumerate() {
        let port = if i < port_map.len() { port_map[i] } else { i };
        if port >= num_outputs || Some(port) == metro_reserved {
            continue;
        }

        if i == 0 {
            // Melody: send immediately
            let msg = MidiMessage::NoteOff(channel, n, velocity);
            let mut buf = vec![0u8; msg.bytes_size()];
            msg.copy_to_slice(&mut buf)?;
            output.send_to_port(port, &buf)?;
        } else {
            // Harmony: humanize note-off (delay = jitter + duration_delta)
            let hn = humanizer.humanize_note_off(n, channel, velocity, port);
            if hn.delay_ms == 0 {
                send_humanized_note(&hn, output)?;
            } else {
                delay_queue.push(hn, now_ms);
            }
        }
    }

    Ok(())
}

// ============================================================================
// CLI-mode router (non-GUI)
// ============================================================================

/// Runs the MIDI routing loop with harmony generation (CLI mode).
#[cfg(not(feature = "gui"))]
pub fn run_router(
    input_port: usize,
    output_ports: &[usize],
    engine: &mut HarmonyEngine,
) -> Result<()> {
    // Create channel for message forwarding from input callback to main loop
    let (tx, rx) = mpsc::channel::<Vec<u8>>();

    // Connect to input port - IMPORTANT: Must keep connection alive
    let _conn_in = connect_input(input_port, tx)?;

    // Create output router
    let mut output_router = OutputRouter::new(output_ports)?;

    // Configure engine voice count to match output count
    let num_outputs = output_router.connection_count();
    engine.set_voice_count(num_outputs);

    // Create humanizer and delay queue (CLI uses default config = disabled)
    let mut humanizer = Humanizer::new(HumanizeConfig::default());
    let mut delay_queue = DelayQueue::new();
    let epoch = Instant::now();
    let now_ms = || epoch.elapsed().as_secs_f64() * 1000.0;

    humanizer.clock_mut().start(now_ms());

    println!("\n========================================");
    println!("MIDI harmony routing active.");
    println!(
        "Key: {:?}, Mode: {} - {}",
        engine.key(),
        engine.mode().number(),
        engine.mode().description()
    );
    println!("Voices: {} (melody + {} chained harmonies)", num_outputs, num_outputs.saturating_sub(1));
    println!("Press Enter to stop.");
    println!("========================================\n");

    // Create a channel to signal when Enter is pressed
    let (stop_tx, stop_rx) = mpsc::channel::<()>();

    // Spawn thread to wait for Enter key
    thread::spawn(move || {
        let stdin = io::stdin();
        let mut handle = stdin.lock();
        let mut line = String::new();
        let _ = handle.read_line(&mut line);
        let _ = stop_tx.send(());
    });

    // Main routing loop
    loop {
        // Check if user pressed Enter (non-blocking)
        if stop_rx.try_recv().is_ok() {
            println!("\nStopping MIDI router...");
            break;
        }

        // Tick humanizer
        let current_ms = now_ms();
        humanizer.tick(current_ms);

        // Drain delay queue
        let current_ms = now_ms();
        for hn in delay_queue.drain_ready(current_ms) {
            let _ = send_humanized_note(&hn, &mut output_router);
        }

        // Try to receive MIDI message with timeout
        match rx.recv_timeout(Duration::from_millis(5)) {
            Ok(message) => {
                let current_ms = now_ms();
                if let Err(e) = process_midi_message(&message, engine, &mut output_router, &mut humanizer, &mut delay_queue, current_ms) {
                    eprintln!("Error processing message: {}", e);
                }
            }
            Err(mpsc::RecvTimeoutError::Timeout) => {
                // No message received, continue loop (allows checking for Enter)
            }
            Err(mpsc::RecvTimeoutError::Disconnected) => {
                eprintln!("Input channel disconnected unexpectedly.");
                break;
            }
        }
    }

    println!("MIDI router stopped.");
    Ok(())
}

/// Processes a single MIDI message through the harmony engine (CLI mode).
#[cfg(not(feature = "gui"))]
fn process_midi_message(
    bytes: &[u8],
    engine: &mut HarmonyEngine,
    output: &mut OutputRouter,
    humanizer: &mut Humanizer,
    delay_queue: &mut DelayQueue,
    now_ms: f64,
) -> Result<()> {
    let msg = match MidiMessage::try_from(bytes) {
        Ok(m) => m,
        Err(_) => {
            output.send_to_first(bytes)?;
            return Ok(());
        }
    };

    match msg {
        MidiMessage::NoteOn(channel, note, velocity) => {
            if velocity == Velocity::MIN {
                handle_note_off(channel, note, velocity, engine, output, humanizer, delay_queue, now_ms)?;
            } else {
                handle_note_on(channel, note, velocity, engine, output, humanizer, delay_queue, now_ms)?;
            }
        }
        MidiMessage::NoteOff(channel, note, velocity) => {
            handle_note_off(channel, note, velocity, engine, output, humanizer, delay_queue, now_ms)?;
        }
        _ => {
            output.send_to_first(bytes)?;
        }
    }

    Ok(())
}

/// Handles Note-On: harmonize and send to outputs (CLI mode).
#[cfg(not(feature = "gui"))]
fn handle_note_on(
    channel: Channel,
    note: Note,
    velocity: Velocity,
    engine: &mut HarmonyEngine,
    output: &mut OutputRouter,
    humanizer: &mut Humanizer,
    delay_queue: &mut DelayQueue,
    now_ms: f64,
) -> Result<()> {
    let notes = engine.harmonize_note_on(note);
    let num_outputs = output.connection_count();

    let port_map = engine.last_port_map();
    for (i, &n) in notes.iter().enumerate() {
        let port = if i < port_map.len() { port_map[i] } else { i };
        if port >= num_outputs {
            continue;
        }

        if i == 0 {
            // Melody: send immediately
            let msg = MidiMessage::NoteOn(channel, n, velocity);
            let mut buf = vec![0u8; msg.bytes_size()];
            msg.copy_to_slice(&mut buf)?;
            output.send_to_port(port, &buf)?;
        } else {
            // Harmony: humanize
            let hn = humanizer.humanize_note_on(n, channel, velocity, port);
            if hn.delay_ms == 0 {
                send_humanized_note(&hn, output)?;
            } else {
                delay_queue.push(hn, now_ms);
            }
        }
    }

    // Debug output
    if notes.len() > 1 {
        let note_strs: Vec<String> = notes.iter()
            .zip(port_map.iter().chain(std::iter::repeat(&0)))
            .map(|(n, p)| format!("{:?}->p{}", n, p))
            .collect();
        println!("[CHAIN] {:?} => [{}]", note, note_strs.join(", "));
    } else {
        println!("[PASS] {:?}", note);
    }

    Ok(())
}

/// Handles Note-Off: release original and harmony notes (CLI mode).
#[cfg(not(feature = "gui"))]
fn handle_note_off(
    channel: Channel,
    note: Note,
    velocity: Velocity,
    engine: &mut HarmonyEngine,
    output: &mut OutputRouter,
    humanizer: &mut Humanizer,
    delay_queue: &mut DelayQueue,
    now_ms: f64,
) -> Result<()> {
    let notes = engine.harmonize_note_off(note);
    let num_outputs = output.connection_count();

    let port_map = engine.last_port_map();
    for (i, &n) in notes.iter().enumerate() {
        let port = if i < port_map.len() { port_map[i] } else { i };
        if port >= num_outputs {
            continue;
        }

        if i == 0 {
            // Melody: send immediately
            let msg = MidiMessage::NoteOff(channel, n, velocity);
            let mut buf = vec![0u8; msg.bytes_size()];
            msg.copy_to_slice(&mut buf)?;
            output.send_to_port(port, &buf)?;
        } else {
            // Harmony: humanize note-off
            let hn = humanizer.humanize_note_off(n, channel, velocity, port);
            if hn.delay_ms == 0 {
                send_humanized_note(&hn, output)?;
            } else {
                delay_queue.push(hn, now_ms);
            }
        }
    }

    Ok(())
}
