[package]
name = "elixir-plugin"
version = "0.0.1"
edition = "2021"
description = "Elixir standalone synth as VST3/CLAP plugin"
authors = ["Contrapunk Team"]
build = "../../plugin/build.rs"

[features]
default = []
embed-ui = []

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
elixir-core = { path = "../elixir-core", features = ["std"] }
elixir-preset = { path = "../elixir-preset" }
nih_plug = { git = "https://github.com/contrapunk-audio/nih-plug.git", features = ["assert_process_allocs"] }
nih_plug_webview = { git = "https://github.com/contrapunk-audio/nih-plug-webview.git" }
serde_json = "1.0"

[dev-dependencies]
assert_no_alloc = { git = "https://github.com/robbert-vdh/rust-assert-no-alloc.git", branch = "feature/nested-permit-forbid", features = ["backtrace", "log"] }
